// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"example/apiwire/cmd/api/handler"
	"example/apiwire/internal/config"
	"example/apiwire/internal/repository"
	"example/apiwire/internal/repository/user"
	user2 "example/apiwire/internal/services/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeAPI(config2 config.AppConfig) (handler.Handler, func()) {
	db, cleanup := repository.NewPostgresConnection(config2)
	userRepo := user.ProvideUserRepo(db)
	userService := user2.ProvideUserService(userRepo)
	userHandler := handler.ProvideUserHandler(userService)
	handlerHandler := handler.NewHandler(userHandler)
	return handlerHandler, func() {
		cleanup()
	}
}

// wire.go:

var MainBindingSet = wire.NewSet(user2.UserServiceSet)

var DBSet = wire.NewSet(repository.PostgresDBSet, user.UserDBSet)

var HandlerSet = wire.NewSet(handler.UserHandlerSet, handler.HandlerSet)
