// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"example/apiwire/cmd/api/handler"
	"example/apiwire/internal/repository/user"
	user2 "example/apiwire/internal/services/user"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAPI(dbConn *gorm.DB) handler.Handler {
	userRepo := user.ProvideUserRepo(dbConn)
	userService := user2.ProvideUserService(userRepo)
	userHandler := handler.ProvideUserHandler(userService)
	handlerHandler := handler.NewHandler(userHandler)
	return handlerHandler
}

// wire.go:

var MainBindingSet = wire.NewSet(user2.UserServiceSet)

var DBSet = wire.NewSet(user.UserDBSet)

var HandlerSet = wire.NewSet(handler.UserHandlerSet, handler.HandlerSet)
